# Generated by Django 3.2.4 on 2021-07-07 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210707_1602'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bill',
            name='unique bill',
        ),
        migrations.RemoveConstraint(
            model_name='consumer',
            name='unique user',
        ),
        migrations.RemoveConstraint(
            model_name='item',
            name='unique item',
        ),
    ]
